# Generated by Django 5.0.3 on 2024-03-15 13:51

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursePicture', models.ImageField(blank=True, null=True, upload_to='coursePicture')),
                ('courseName', models.CharField(blank=True, max_length=150, null=True)),
                ('coursePrice', models.IntegerField(blank=True, null=True)),
                ('madeBy', models.CharField(blank=True, max_length=150, null=True)),
                ('courseDuration', models.CharField(max_length=50)),
                ('studentOnCourse', models.IntegerField(default=0)),
                ('AboutCourse', tinymce.models.HTMLField(blank=True)),
                ('courseCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
        ),
        migrations.CreateModel(
            name='OrdersPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('buycourse', models.CharField(max_length=500)),
                ('amount', models.CharField(max_length=100)),
                ('payment_id', models.CharField(max_length=150)),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_link', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures')),
                ('phone', models.CharField(blank=True, default='', max_length=14, null=True)),
                ('address', models.TextField(blank=True, default='', null=True)),
                ('birthdate', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
