# Generated by Django 5.0.3 on 2024-03-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseFile',
            field=models.FileField(blank=True, null=True, upload_to='coursePdf'),
        ),
    ]
