# Generated by Django 5.0.3 on 2024-03-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_course_coursefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referral_code_used',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
