# Generated by Django 5.0.3 on 2024-03-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userprofile_address_userprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursePicture', models.ImageField(blank=True, null=True, upload_to='coursePicture')),
                ('courseName', models.CharField(blank=True, max_length=150, null=True)),
                ('coursePrice', models.IntegerField(blank=True, null=True)),
                ('madeBy', models.CharField(blank=True, max_length=150, null=True)),
                ('courseDuration', models.DurationField()),
                ('studentonCourse', models.IntegerField(default=0)),
            ],
        ),
    ]
