# Generated by Django 5.0.3 on 2024-03-14 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='studentonCourse',
            new_name='studentOnCourse',
        ),
    ]
