# Generated by Django 5.0.3 on 2024-03-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_studentoncourse_course_studentoncourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseDuration',
            field=models.TimeField(),
        ),
    ]
