# Generated by Django 5.0.3 on 2024-03-16 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
    ]
