# Generated by Django 5.0.3 on 2024-03-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_course_courseduration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseDuration',
            field=models.CharField(max_length=50),
        ),
    ]
