# Generated by Django 5.0.3 on 2024-03-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_course_courseduration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseCatagory',
            field=models.CharField(default='', max_length=200),
        ),
    ]
