# Generated by Django 5.0.3 on 2024-03-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_event_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
