# Generated by Django 5.0.3 on 2024-03-14 12:11

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_course_aboutcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='AboutCourse',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
