# Generated by Django 5.0.3 on 2024-03-14 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_course_aboutcourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='age',
            new_name='birthdate',
        ),
    ]
