# Generated by Django 5.0.3 on 2024-03-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='studentOnCourse',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='sales',
            name='lifetime_sale',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sales',
            name='one_day_sale',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sales',
            name='one_month_sale',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sales',
            name='one_week_sale',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sales',
            name='one_year_sale',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
