# Generated by Django 5.0.3 on 2024-03-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_course_studentoncourse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_email_varified',
            field=models.BooleanField(default=False),
        ),
    ]
