# Generated by Django 5.0.3 on 2024-03-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_userprofile_is_email_varified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coursePicture',
            field=models.ImageField(blank=True, null=True, upload_to='coursePicture/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
