# Generated by Django 5.0.3 on 2024-03-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_userprofile_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthdate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
